In [1]:
import pandas as pd

print("Pandas is working!")

Pandas is working!

In [2]:
import pandas as pd

data = {
    "text": [
        "I love this product",
        "This service is terrible",
        "The update is good",
        "I dislike the new design"
    ]
}

df = pd.DataFrame(data)

df

                       text
0       I love this product
1  This service is terrible
2        The update is good
3  I dislike the new design

In [3]:
import pandas as pd

In [4]:
import pandas as pd

df = pd.read_csv("F:\NSU\Semester 12 Summer 2026\CSE445\Project\data\twitter_training.csv")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: malformed \N character escape (2900598880.py, line 3)

In [5]:
import pandas as pd

df = pd.read_csv(r"F:\NSU\Semester 12 Summer 2026\CSE445\Project\data\twitter_training.csv")

In [6]:
df.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 74681 entries, 0 to 74680
Data columns (total 4 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   2401                                                   74681 non-null  int64
 1   Borderlands                                            74681 non-null  str
 2   Positive                                               74681 non-null  str
 3   im getting on borderlands and i will murder you all ,  73995 non-null  str
dtypes: int64(1), str(3)
memory usage: 2.3 MB

In [8]:
df.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    686
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(2700)

In [10]:
df = df.drop_duplicates()

In [11]:
df.to_csv("../data/cleaned_dataset.csv", index=False)